// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa1osYvgCG4T4yx_wYvuEVwWVxaIQTCT4',
    appId: '1:1007255116614:web:d7158155f5d8509096a347',
    messagingSenderId: '1007255116614',
    projectId: 'spotify-ef6c7',
    authDomain: 'spotify-ef6c7.firebaseapp.com',
    storageBucket: 'spotify-ef6c7.firebasestorage.app',
    measurementId: 'G-BDBH4N7N3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqPAXkE2VIQpqPHou0P1Qusf9EOU5eIhs',
    appId: '1:1007255116614:android:e05f7daf15ce81f096a347',
    messagingSenderId: '1007255116614',
    projectId: 'spotify-ef6c7',
    storageBucket: 'spotify-ef6c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpbxFJlGeriKN7FtA-evDsgN2lw_tx3PM',
    appId: '1:1007255116614:ios:559812a23be886da96a347',
    messagingSenderId: '1007255116614',
    projectId: 'spotify-ef6c7',
    storageBucket: 'spotify-ef6c7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpbxFJlGeriKN7FtA-evDsgN2lw_tx3PM',
    appId: '1:1007255116614:ios:559812a23be886da96a347',
    messagingSenderId: '1007255116614',
    projectId: 'spotify-ef6c7',
    storageBucket: 'spotify-ef6c7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa1osYvgCG4T4yx_wYvuEVwWVxaIQTCT4',
    appId: '1:1007255116614:web:31570d9c8e81401996a347',
    messagingSenderId: '1007255116614',
    projectId: 'spotify-ef6c7',
    authDomain: 'spotify-ef6c7.firebaseapp.com',
    storageBucket: 'spotify-ef6c7.firebasestorage.app',
    measurementId: 'G-JKTNYW02Q8',
  );
}
