// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfKeaAm9YPO_qBjiubdf-cC8RvdQG-pU',
    appId: '1:188029203691:web:808a02efa164f221097aae',
    messagingSenderId: '188029203691',
    projectId: 'blogapp-f76a3',
    authDomain: 'blogapp-f76a3.firebaseapp.com',
    storageBucket: 'blogapp-f76a3.firebasestorage.app',
    measurementId: 'G-74HYX0C7LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJE0lL5WIvi1G-z2Nbb53eAXNAQb-kwBU',
    appId: '1:188029203691:android:084f6f09e35a9371097aae',
    messagingSenderId: '188029203691',
    projectId: 'blogapp-f76a3',
    storageBucket: 'blogapp-f76a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUTYUaq-kZHjyk4-3nIpgMoflQ4biUQZg',
    appId: '1:188029203691:ios:fee815586a786117097aae',
    messagingSenderId: '188029203691',
    projectId: 'blogapp-f76a3',
    storageBucket: 'blogapp-f76a3.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUTYUaq-kZHjyk4-3nIpgMoflQ4biUQZg',
    appId: '1:188029203691:ios:fee815586a786117097aae',
    messagingSenderId: '188029203691',
    projectId: 'blogapp-f76a3',
    storageBucket: 'blogapp-f76a3.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzfKeaAm9YPO_qBjiubdf-cC8RvdQG-pU',
    appId: '1:188029203691:web:21cae946b68739f4097aae',
    messagingSenderId: '188029203691',
    projectId: 'blogapp-f76a3',
    authDomain: 'blogapp-f76a3.firebaseapp.com',
    storageBucket: 'blogapp-f76a3.firebasestorage.app',
    measurementId: 'G-3PRF6HY2VL',
  );
}
